### ISSUE TITLE
UnsupportedOperationException: JsonNull

### ISSUE THREAD

**Issue by bimawa** [johna1203/getGists#18]
On AppCode 3.1

**Comment by melvyn-sopacua** [comment]
Also in PhpStorm 8.0.2. Trace:

    JsonNull
    java.lang.UnsupportedOperationException: JsonNull
        at com.google.gson.JsonElement.getAsString(JsonElement.java:191)
        at com.kodokux.github.GithubGetGistAction$1.consume(GithubGetGistAction.java:77)
        at com.kodokux.github.GithubGetGistAction$1.consume(GithubGetGistAction.java:57)
        at com.kodokux.github.GithubGetGistAction$2.onSuccess(GithubGetGistAction.java:109)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl$9$2.run(ProgressManagerImpl.java:557)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:318)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:706)
        at java.awt.EventQueue$3.run(EventQueue.java:704)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
        at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by silvafabio** [comment]
Try this on: https://plugins.jetbrains.com/plugin/11080-use-gists
