### ISSUE TITLE
Doesn't work with two factor authentication

### ISSUE THREAD

**Issue by stefanwalther** [johna1203/getGists#20]
Hi,

doesn't work with two-factor authentication on GitHub, even if the test-button where I enter the credentials tells me that the login succeeded.

Regards
Stefan

**Comment by stefanwalther** [comment]
Getting this error message, having configured a token now:

JsonNull
java.lang.UnsupportedOperationException: JsonNull
    at com.google.gson.JsonElement.getAsString(JsonElement.java:191)
    at com.kodokux.github.GithubGetGistAction$1.consume(GithubGetGistAction.java:77)
    at com.kodokux.github.GithubGetGistAction$1.consume(GithubGetGistAction.java:57)
    at com.kodokux.github.GithubGetGistAction$2.onSuccess(GithubGetGistAction.java:109)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1$2.run(ProgressManagerImpl.java:153)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:345)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:329)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:857)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by silvafabio** [comment]
Try this on: https://plugins.jetbrains.com/plugin/11080-use-gists
