### ISSUE TITLE
IllegalStateException,GithubSettings.getAuthData

### ISSUE THREAD

**Issue by leaderliang** [johna1203/getGists#29]
Hi, johna1203:
I have encountered some problems on android studio；

`
java.lang.IllegalStateException: Single account auth is deprecated at org.jetbrains.plugins.github.util.GithubSettings.getAuthData(GithubSettings.java:129) at com.kodokux.github.GithubGetGistAction$2.run(GithubGetGistAction.java:116) at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157) at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580) at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525) at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85) at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144) at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395) at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745)
`

**Comment by mykhaliuk** [comment]
Hi!

On `WebStorm 2019.3.3
Build #WS-193.6494.34, built on February 11, 2020` with token auth method have the same problem:
```
2020-03-08 20:31:24,625 [ 986519]  ERROR - intellij.openapi.progress.Task - Single account auth is deprecated 
```
